import { useEffect } from 'react';

export default function PrivacyPage({ navigate }: { navigate: (path: string) => void }) {
  useEffect(() => { window.scrollTo(0, 0); }, []);
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-100">
      <header className="px-6 py-5 border-b border-slate-200 dark:border-slate-800">
        <div className="max-w-2xl mx-auto flex items-center gap-4">
          <button
            onClick={() => navigate('/')}
            className="text-sm text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100 transition-colors"
          >
            ← Back
          </button>
          <button onClick={() => navigate('/')} className="flex items-center gap-2 ml-auto">
            <svg viewBox="0 0 32 32" className="w-6 h-6" xmlns="http://www.w3.org/2000/svg">
              <rect x="2" y="2" width="28" height="28" rx="3" fill="#1e293b" />
              <rect x="5" y="5" width="22" height="22" rx="1.5" fill="#f8fafc" />
              <rect x="7" y="7" width="18" height="9" rx="1" fill="#818cf8" />
              <rect x="7" y="16" width="18" height="9" rx="0" fill="#6366f1" />
              <circle cx="16" cy="13" r="3.5" fill="#fde68a" />
            </svg>
            <span className="text-slate-900 dark:text-slate-100 font-semibold text-sm">ArtSlaw</span>
          </button>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="font-serif text-3xl font-semibold text-slate-900 dark:text-slate-50 mb-2">Privacy Policy</h1>
        <p className="text-slate-400 dark:text-slate-500 text-sm mb-10">Last updated: April 2026</p>

        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-6">
          ArtSlaw ("we", "us", or "our") is committed to protecting your privacy. This policy explains what information we collect, how we use it, and your choices.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Information We Collect</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-3">
          <strong className="text-slate-700 dark:text-slate-300">Account information.</strong> When you sign up, authentication is handled by Clerk. We receive your name and email address as provided through that sign-up flow. We do not store passwords.
        </p>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-3">
          <strong className="text-slate-700 dark:text-slate-300">Conversation history.</strong> When you start a tour, we store the exhibition URL you submitted, the questions you ask, and the responses generated by ArtSlaw. This is saved to a MongoDB database and is tied to your account.
        </p>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          <strong className="text-slate-700 dark:text-slate-300">Usage data.</strong> We may collect basic anonymised usage signals (e.g. pages visited, errors encountered) to help us improve the service. This does not include the content of your conversations.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">How We Use Your Information</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-3">
          We use your information solely to provide and improve ArtSlaw. Specifically:
        </p>
        <ul className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm list-disc list-inside space-y-1 mb-3">
          <li>To authenticate you and display your conversation history</li>
          <li>To generate AI-powered tour responses based on the exhibitions you submit</li>
          <li>To diagnose bugs and improve reliability</li>
        </ul>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          We do not sell your data to third parties. We do not use your conversations for advertising.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Data Storage & Security</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-3">
          Your account data is managed by Clerk, which maintains its own security practices and certifications. Conversation data is stored in MongoDB Atlas. We use HTTPS for all data in transit.
        </p>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          You can delete your conversation history at any time from within the app. To delete your account and all associated data, contact us at the address below.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Third-Party Services</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          ArtSlaw uses the following third-party services: Clerk (authentication), MongoDB Atlas (data storage), and an AI model provider to generate tour responses. Each of these services has its own privacy policy.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Contact</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          If you have questions about this policy or want to request deletion of your data, email us at{' '}
          <a href="mailto:hello@artslaw.io" className="text-indigo-600 dark:text-indigo-400 hover:underline">hello@artslaw.io</a>.
        </p>
      </main>

      <footer className="px-6 py-6 text-center border-t border-slate-200 dark:border-slate-800 mt-8">
        <p className="text-slate-400 dark:text-slate-600 text-xs flex flex-wrap items-center justify-center gap-x-2">
          <span>&copy; {new Date().getFullYear()} ArtSlaw</span>
          <span className="text-slate-300 dark:text-slate-700">·</span>
          <button onClick={() => navigate('/privacy')} className="hover:text-slate-600 dark:hover:text-slate-400 transition-colors">Privacy</button>
          <span className="text-slate-300 dark:text-slate-700">·</span>
          <button onClick={() => navigate('/terms')} className="hover:text-slate-600 dark:hover:text-slate-400 transition-colors">Terms</button>
        </p>
      </footer>
    </div>
  );
}
