import { useEffect } from 'react';

export default function TermsPage({ navigate }: { navigate: (path: string) => void }) {
  useEffect(() => { window.scrollTo(0, 0); }, []);
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-100">
      <header className="px-6 py-5 border-b border-slate-200 dark:border-slate-800">
        <div className="max-w-2xl mx-auto flex items-center gap-4">
          <button
            onClick={() => navigate('/')}
            className="text-sm text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100 transition-colors"
          >
            ← Back
          </button>
          <button onClick={() => navigate('/')} className="flex items-center gap-2 ml-auto">
            <svg viewBox="0 0 32 32" className="w-6 h-6" xmlns="http://www.w3.org/2000/svg">
              <rect x="2" y="2" width="28" height="28" rx="3" fill="#1e293b" />
              <rect x="5" y="5" width="22" height="22" rx="1.5" fill="#f8fafc" />
              <rect x="7" y="7" width="18" height="9" rx="1" fill="#818cf8" />
              <rect x="7" y="16" width="18" height="9" rx="0" fill="#6366f1" />
              <circle cx="16" cy="13" r="3.5" fill="#fde68a" />
            </svg>
            <span className="text-slate-900 dark:text-slate-100 font-semibold text-sm">ArtSlaw</span>
          </button>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="font-serif text-3xl font-semibold text-slate-900 dark:text-slate-50 mb-2">Terms of Service</h1>
        <p className="text-slate-400 dark:text-slate-500 text-sm mb-10">Last updated: April 2026</p>

        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-6">
          By accessing or using ArtSlaw ("the Service"), you agree to be bound by these Terms of Service. Please read them carefully before using the Service.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Use of the Service</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-3">
          ArtSlaw is a tool for exploring publicly available gallery and museum exhibitions through AI-generated conversational tours. You may use the Service for personal, non-commercial purposes.
        </p>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          You agree not to misuse the Service — including submitting content that is unlawful, abusive, or intended to circumvent rate limits or access controls. We reserve the right to suspend accounts that violate these terms.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">AI-Generated Content</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm mb-3">
          Responses generated by ArtSlaw are produced by an AI model and are provided for informational and educational purposes only. They may contain inaccuracies or omissions. Do not rely on them as authoritative sources about artworks, artists, or institutions.
        </p>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          ArtSlaw does not claim copyright over AI-generated responses. However, you use this content at your own discretion and risk.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">User Content</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          You retain ownership of the exhibition URLs and questions you submit. By submitting content, you grant us a limited licence to process it in order to provide the Service. We do not use your content to train AI models or for purposes beyond operating ArtSlaw.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Availability & Changes</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          We aim to keep ArtSlaw available but cannot guarantee uninterrupted access. We may modify or discontinue features at any time. We may also update these Terms — continued use of the Service after changes constitutes acceptance.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Termination</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          You may stop using ArtSlaw at any time. We may terminate or suspend your access if you breach these Terms. Upon termination, your conversation data will be retained for a reasonable period before deletion, unless you request immediate removal.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Disclaimer of Warranties</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          The Service is provided "as is" without warranties of any kind. To the fullest extent permitted by law, we disclaim all implied warranties including merchantability, fitness for a particular purpose, and non-infringement.
        </p>

        <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mt-8 mb-2">Contact</h2>
        <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-sm">
          Questions about these Terms? Reach us at{' '}
          <a href="mailto:hello@artslaw.io" className="text-indigo-600 dark:text-indigo-400 hover:underline">hello@artslaw.io</a>.
        </p>
      </main>

      <footer className="px-6 py-6 text-center border-t border-slate-200 dark:border-slate-800 mt-8">
        <p className="text-slate-400 dark:text-slate-600 text-xs flex flex-wrap items-center justify-center gap-x-2">
          <span>&copy; {new Date().getFullYear()} ArtSlaw</span>
          <span className="text-slate-300 dark:text-slate-700">·</span>
          <button onClick={() => navigate('/privacy')} className="hover:text-slate-600 dark:hover:text-slate-400 transition-colors">Privacy</button>
          <span className="text-slate-300 dark:text-slate-700">·</span>
          <button onClick={() => navigate('/terms')} className="hover:text-slate-600 dark:hover:text-slate-400 transition-colors">Terms</button>
        </p>
      </footer>
    </div>
  );
}
